### ISSUE TITLE
architecture: 와이어 프레임 설계

### ISSUE THREAD

**Issue by jaemin-Yoo** [jaemin-Yoo/AndroidPlayground#1]
### Task
- [x] NoteApp 와이어 프레임 설계
  - [x] 메모 목록 화면
  - [x] 메모 작성 화면

### Details
- Figma로 와이어 프레임 설계하기
