### ISSUE TITLE
architecture-mvc: 메모 작성 화면 구현

### ISSUE THREAD

**Issue by jaemin-Yoo** [jaemin-Yoo/AndroidPlayground#5]
### Task
- [x] 제목, 내용 UI 구현
- [x] 메모 색상 변경 기능 구현
- [x] 뒤로가기, 완료 버튼 구현
- [x] 메모 저장 기능 구현

### Details
<img src="https://github.com/jaemin-Yoo/AndroidPlayground/assets/68587360/0901211b-7ec9-4e92-a1c7-c365c4034335" width="240px" />
