### ISSUE TITLE
architecture-mvc: 메모 목록 화면 구현

### ISSUE THREAD

**Issue by jaemin-Yoo** [jaemin-Yoo/AndroidPlayground#6]
### Task
- [x] Appbar 구현
- [x] 메모 목록 구현
- [x] 메모 추가 기능 구현
- [x] 메모 수정 기능 구현
- [x] 메모 삭제 기능 구현

### Details
<img src="https://github.com/jaemin-Yoo/AndroidPlayground/assets/68587360/634291ea-c235-4fdc-a0e1-cf215a43bf3a" width="240px" />
